// @ts-check
/**
 * Print the PowerShell that creates the board's SharePoint lists.
 *
 * Run it, read what it says, then run that against a TEST site first:
 *
 *     node tools/provision.mjs > provision-lists.ps1
 *
 * It only prints. It connects to nothing and changes nothing, so it is safe to run
 * and safe to hand to IT to read before anything happens.
 *
 * ## Why generate it rather than write it
 *
 * The columns come from src/adapters/sharepointSchema.js — the same file the adapter
 * reads and writes through. Hand-written provisioning would drift from the adapter
 * eventually, and the symptom would be a field that silently stops saving. Generating
 * it means there is one place to change and no way for the two to disagree.
 *
 * ## What it needs
 *
 * PnP.PowerShell, which most Microsoft 365 admins already have:
 *     Install-Module PnP.PowerShell -Scope CurrentUser
 *
 * Whoever runs it needs permission to create lists on the target site.
 */

import {
  SCHEMA, KEY_COLUMN, columnsFor, SP_FIELD_TYPE,
  COUNTER_LIST, COUNTER_KEY, COUNTER_COLUMN
} from '../src/adapters/sharepointSchema.js';

const L = [];
const say = (s) => L.push(s === undefined ? '' : s);

say('<#');
say('  Creates the lists for the Technical Operations & Innovation board.');
say('');
say('  GENERATED by tools/provision.mjs from src/adapters/sharepointSchema.js.');
say('  Do not edit this file by hand - change the schema and generate it again,');
say('  or the lists and the app will drift apart.');
say('');
say('  Run against a TEST site first. It is safe to re-run: every step checks');
say('  whether the thing already exists.');
say('');
say('  Needs PnP.PowerShell and permission to create lists on the site.');
say('#>');
say('');
say('param(');
say('  [Parameter(Mandatory = $true)]');
say('  [string]$SiteUrl   # e.g. https://contoso.sharepoint.com/sites/TechOpsBoard');
say(')');
say('');
say('$ErrorActionPreference = "Stop"');
say('');
say('Write-Host "Connecting to $SiteUrl ..." -ForegroundColor Cyan');
say('Connect-PnPOnline -Url $SiteUrl -Interactive');
say('');

/* ---------------------------------------------------------------- helpers */

say('function Ensure-BoardList {');
say('  param([string]$Title)');
say('  $existing = Get-PnPList -Identity $Title -ErrorAction SilentlyContinue');
say('  if ($existing) {');
say('    Write-Host "  list $Title already exists" -ForegroundColor DarkGray');
say('  } else {');
say('    New-PnPList -Title $Title -Template GenericList -OnQuickLaunch:$false | Out-Null');
say('    Write-Host "  created list $Title" -ForegroundColor Green');
say('  }');
say('}');
say('');
say('function Ensure-BoardField {');
say('  param([string]$List, [string]$Name, [string]$Type)');
say('  $existing = Get-PnPField -List $List -Identity $Name -ErrorAction SilentlyContinue');
say('  if ($existing) {');
say('    Write-Host "    field $Name already exists" -ForegroundColor DarkGray');
say('    return');
say('  }');
say('  # InternalName is set explicitly and matches the display name, because Graph');
say('  # cannot tell you internal names later and a mismatch is invisible until a');
say('  # field silently stops saving.');
say('  Add-PnPField -List $List -DisplayName $Name -InternalName $Name -Type $Type `');
say('    -AddToDefaultView | Out-Null');
say('  Write-Host "    added field $Name ($Type)" -ForegroundColor Green');
say('}');
say('');
say('function Ensure-BoardIndex {');
say('  param([string]$List, [string]$Name)');
say('  # Indexes matter once a list passes the 5,000-item view threshold, which the');
say('  # entries list reaches in about a year. Cheaper to do now than to retrofit.');
say('  try {');
say('    Set-PnPField -List $List -Identity $Name -Values @{ Indexed = $true } | Out-Null');
say('    Write-Host "    indexed $Name" -ForegroundColor Green');
say('  } catch {');
say('    Write-Host "    could not index $Name : $_" -ForegroundColor Yellow');
say('  }');
say('}');
say('');

/* ------------------------------------------------------------------ lists */

const cols = Object.keys(SCHEMA);
say('Write-Host ""');
say('Write-Host "Creating ' + (cols.length + 1) + ' lists ..." -ForegroundColor Cyan');
say('');

cols.forEach(function (col) {
  const spec = SCHEMA[col];
  say('# ---- ' + col + ' ----');
  say('Write-Host "' + spec.list + '" -ForegroundColor White');
  say('Ensure-BoardList -Title "' + spec.list + '"');

  // The app's own record id lives in Title, which every list already has. That
  // avoids fighting a required empty field on every single write.
  say('# The app id lives in ' + KEY_COLUMN + ', which every list has by default.');
  say('Ensure-BoardIndex -List "' + spec.list + '" -Name "' + KEY_COLUMN + '"');

  columnsFor(col).forEach(function (c) {
    say('Ensure-BoardField -List "' + spec.list + '" -Name "' + c.name +
        '" -Type "' + SP_FIELD_TYPE[c.kind] + '"');
  });

  (spec.indexes || []).forEach(function (name) {
    say('Ensure-BoardIndex -List "' + spec.list + '" -Name "' + name + '"');
  });

  say('');
});

/* ---------------------------------------------------------------- counter */

say('# ---- the action counter ----');
say('# One row, holding the next action number. Created here so the app never has to');
say('# take the create path, where two people adding an action at the same moment');
say('# would be racing to make the row.');
say('Write-Host "' + COUNTER_LIST + '" -ForegroundColor White');
say('Ensure-BoardList -Title "' + COUNTER_LIST + '"');
say('Ensure-BoardField -List "' + COUNTER_LIST + '" -Name "' + COUNTER_COLUMN + '" -Type "Number"');
say('');
say('$counter = Get-PnPListItem -List "' + COUNTER_LIST + '" `');
say('  -Query "<View><Query><Where><Eq><FieldRef Name=\'' + KEY_COLUMN + '\'/>' +
    '<Value Type=\'Text\'>' + COUNTER_KEY + '</Value></Eq></Where></Query></View>"');
say('if ($counter) {');
say('  Write-Host "    counter row already exists" -ForegroundColor DarkGray');
say('} else {');
say('  Add-PnPListItem -List "' + COUNTER_LIST + '" -Values @{');
say('    "' + KEY_COLUMN + '" = "' + COUNTER_KEY + '"; "' + COUNTER_COLUMN + '" = 1');
say('  } | Out-Null');
say('  Write-Host "    created the counter row, starting at 1" -ForegroundColor Green');
say('}');
say('');

/* ------------------------------------------------------------ permissions */

const settingsLists = ['people', 'tabs', 'settings']
  .map(function (c) { return SCHEMA[c].list; })
  .concat([COUNTER_LIST]);
const contentLists = ['entries', 'projects', 'issues', 'actions', 'meetings']
  .map(function (c) { return SCHEMA[c].list; });
const restrictedLists = [SCHEMA.projectDetails.list];

say('Write-Host ""');
say('Write-Host "Done." -ForegroundColor Cyan');
say('Write-Host ""');
say('Write-Host "PERMISSIONS - still to do by hand, deliberately." -ForegroundColor Yellow');
say(String.raw`Write-Host "The app discovers what it may write by being refused, so these three"`);
say(String.raw`Write-Host "groups are what make the read-only behaviour work:"`);
say('Write-Host ""');
say('Write-Host "  Owner-only (everyone else Read):" -ForegroundColor White');
settingsLists.forEach(function (l) { say('Write-Host "    ' + l + '"'); });
say('Write-Host ""');
say('Write-Host "  Team can Contribute:" -ForegroundColor White');
contentLists.forEach(function (l) { say('Write-Host "    ' + l + '"'); });
say('Write-Host ""');
say('Write-Host "  RESTRICTED - only people who may see project value:" -ForegroundColor Red');
restrictedLists.forEach(function (l) { say('Write-Host "    ' + l + '"'); });
say('Write-Host ""');
say('Write-Host "  This last one is the whole point of splitting those fields out."');
say('Write-Host "  Anyone who can read this list sees every project value on the board -"');
say('Write-Host "  access is per list, so it is all-or-nothing. Anyone who cannot read it"');
say('Write-Host "  never receives the figures at all, rather than being shown a page that"');
say('Write-Host "  politely does not draw them."');
say('Write-Host ""');
say('Write-Host "Break inheritance on each list, then set the two groups. Doing this"');
say('Write-Host "by hand is on purpose: a script that rearranges permissions is not"');
say('Write-Host "something anyone should run without reading it first."');
say('Write-Host ""');
say('Write-Host "Then put the site id into src/config.js and set mode to ' +
    "'sharepoint'" + '."');

process.stdout.write(L.join('\n') + '\n');
